m2 solution
Signed-off-by: Michael Yuan <michael@secondstate.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,7 @@ on:
         required: true
         default: 'info'
   push:
-    branches: [ main ]
+    branches: [ main, m2 ]
   pull_request:
     branches: [ main ]
 
@@ -57,6 +57,14 @@ jobs:
         resp=$(curl http://localhost:8002/compute -X POST -d @order.json)
         echo "$resp"
         if [[ $resp == *"21.65"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        resp=$(curl http://localhost:8002/compute -X POST -d @order2.json)
+        echo "$resp"
+        if [[ $resp == *"error"* ]]; then
           echo -e "Execution Success!"
         else
           echo -e "Execution Fail!"
